name: Generate Docker Image

on:
  push:
    branches:
      - main

jobs:
  generate-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Build Docker image
        run: docker build -t cat .
        
      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

      - name: Deploy the tagged Docker image to GitHub Packages
        run: |
          docker tag cat "ghcr.io/dolbyio-samples/dolbyio-web-conference-access-control:latest"
          docker push "ghcr.io/dolbyio-samples/dolbyio-web-conference-access-control:latest"
